# Lecture 9: Machine Learning

In [ ]:
#Install the package numpy and scikit-learn


In [2]:
#import the packages (numpy and linear_model from scikit)
import numpy as np

## Introduction to numpy

In [5]:
#Create your first numpy array in 1 dimension
array = np.array([1, 2, 3, 4, 5, 6])
print(array)

[1 2 3 4 5 6]


In [6]:
#Create your first 2 dimensionnal arry
l = [[1, 2, 3], [4, 5, 6]]
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print('-'*20)
print(l)

[[1 2 3]
 [4 5 6]]
--------------------
[[1, 2, 3], [4, 5, 6]]


In [ ]:
#getting access to numpy array items
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array[0][1])

In [ ]:
#the copy and the view
list0 = [1, 2, 3]
list1 = list0.copy()
list1[0] = 55
print(list1)
print(list0)

In [ ]:
#the copy and the view
arr0 = np.array([1, 2, 3])
arr1 = arr0.view()
arr2 = arr0.copy()
arr1[1]= 50
arr2[1] = 50000
print(arr0)
print(arr1)
print(arr2)

In [13]:
array = np.array([[1, 20000000, 3], [4, 5, 6]])
print(array)

[[       1 20000000        3]
 [       4        5        6]]


In [7]:
#The shape of an array
array = np.array([1, 2, 3, 4, 5, 6])
print(array.shape)

(6,)


In [11]:
#reshape your array from 1D to 2D
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#reshape your array from 1D to 2D
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((6,1)))

In [12]:
#reshape your array from 1D to another D (with -1)
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((-1,2)))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#reshape your array from 1D to another D (with -1)
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((-1,1)))

In [ ]:
#The hstack
array0 = np.array([1, 2, 3, 4, 5, 6])
array0 = array.reshape((-1,1))
array1 = np.array([7, 8, 9, 10, 11, 12])
array1 = array1.reshape((-1,1))
print(array0)
print('-'*20)
print(array1)
print('-'*20)
print(np.hstack([array0, array1]))

In [ ]:
#The avantage of numpy, the use of array for addition or multiplication for example
l = [1, 2, 3, 4]
arr = np.array([1,2,3,4])
# print(l +2 )
print(arr +2 )
print(arr *2 )
print(l + l )
print(arr + arr )

In [ ]:
#YOUR TURN (10 minutes)
#Change this array [1,5,9,31,45,78]
#into this one:
#[[1 5],
#[9 31],
#[45 78]]
arr = np.array([1,5,9,31,45,78])
print(arr.reshape((3,2)))
print(arr.reshape((-1,2)))
print(arr.reshape((3,-1)))